services:
  app:
    build: .
    environment:
      - PROD=1
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    container_name: kwikquiz-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
